apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac-{{VERSION}}-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tic-tac-app
      version: {{VERSION}}
  template:
    metadata:
      labels:
        app: tic-tac-app
        version: {{VERSION}}
    spec:
      containers:
        - name: tic-tac-container
          image: blue-green-deploy:{{IMAGE_TAG}}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
