apiVersion: v1
kind: Service
metadata:
  name: javawebapp-service
spec:
  selector:
    app: java-web-app
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
