apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac-green-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tic-tac-app
      version: green
  template:
    metadata:
      labels:
        app: tic-tac-app
        version: green
    spec:
      containers:
        - name: tic-tac-container
          image: dilipopseng/titacapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
