apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac-test-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tic-tac-app
      version: v1
  template:
    metadata:
      labels:
        app: tic-tac-app
        version: v1
    spec:
      containers:
        - name: tic-tac-container
          image: blue-green-deploy:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
