apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac-deployment-v2
  namespace: webapps
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tic-tac-app
      version: v2
  template:
    metadata:
      labels:
        app: tic-tac-app
        version: v2
    spec:
      containers:
        - name: tic-tac-container
          image: dilipopseng/tictac:18
          imagePullPolicy: Always
          ports:
            - containerPort: 80
