apiVersion: v1
kind: Service
metadata:
  name: tictac-service
  namespace: webapps
spec:
  selector:
    app: tic-tac-app
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
