apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac-app
  namespace: webapps
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tictac
  template:
    metadata:
      labels:
        app: tictac
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: tictac
          image: dilipopseng/tictac:26
          imagePullPolicy: Always
          ports:
            - containerPort: 80

###
